language: node_js

cache:
  npm: true
  
# safelist
branches:
  only:
  - master

node_js: stable

install:
  - npm install 

scripts:
  - npm run content:build

after_success:
  - cp {CNAME,favicon.ico,avatar.jpeg} docs/
  - git add .
  - git commit -m "feat:update docs"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" HEAD:master